name: psuh to docker hub
description: This workflow build tge image and push to dockerhub
on:
  push:
    branches:
      - main
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write 
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_KEY: ${{ secrets.DOCKER_PASSWORD }}
      VERSION: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/post-api:dev
          provenance: true    
          sbom: true
